### ISSUE TITLE
Comma/period at the end of the line wraps without the word.

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#5]
<img width="533" alt="Screen Shot 2021-03-25 at 5 27 09 PM" src="https://user-images.githubusercontent.com/170009/112551660-5c1a4f80-8d8f-11eb-914d-3314dac8b85c.png">

**Comment by mimshwright** [comment]
Copying over info from Trello.

Actual:
In cases where unbroken text contains a tag, the word is split into multiple parts. E.g. "The<i>saurus</i>" results in "The" + "_saurus_". This also affects alignment especially in Justified text where it might appear as 
The   dinosaur   reads   the
The          _saurus_            .

Expected:
When a block of characters contains a tag, it should only be wrapped to the next line if there are spaces or dashes around the tag. 
e.g. "<b><i>Super</i>hero</b>!" Would be parsed into "<b><i>Super</i></b>", "<b>hero</b>", and "!" but should act as one block for the purposes of word wrapping and alignment.

**Comment by mimshwright** [comment]
Example of justify content
![image](https://user-images.githubusercontent.com/141928/112738010-6a49a680-8f1c-11eb-9afa-4603cfa6a2b0.png)

**Comment by mimshwright** [comment]
The fix for this will require a rework of how the text is parsed. Currently, splits up text into regions with different tags then splits the text by whitespace. However, it doesn't currently deal with the case of a single block of text without whitespace that should be treated as a single word / block. 

I made an attempt to fix this by essentially creating a buffer of word-segments that waits to be positioned until a whitespace is encountered, but the results weren't great. I'm planning to try again where I try to add more metadata to the parsed text tokens indicating where the words should be broken up.

**Comment by mimshwright** [comment]
Check #18 for another example.

**Comment by mimshwright** [comment]
To give you an update, I'm working on a different approach to lexing / parsing the text that I hope will give more flexibility. Rather than breaking things up by tags and spaces, it'll first build more of a tree of tags and strings where each node can contain more of the same. That way it should be much easier to model lines, words, paragraphs, or to even treat each character in the words as a token. I'll hopefully have this sorted in the next couple of days.
